#!/usr/bin/env python
import argparse

import tensorflow as tf

from lib.LSTM import LSTM


def main():
    description = 'LSTM recurrent neural network trainer'

    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('-m',
                        '--model',
                        help='name of model to train',
                        required=True,
                        nargs=1)

    parser.add_argument('-l',
                        '--length',
                        help='maximum length of a analyzed sequences',
                        required=False,
                        default=[25],
                        type=int,
                        nargs=1)

    parser.add_argument('-i',
                        '--iterations',
                        help='maximum number of training iterations',
                        required=False,
                        default=[100000],
                        type=int,
                        nargs=1)

    parser.add_argument('-tl',
                        '--test-length',
                        help='the generated test sequence length',
                        required=False,
                        default=[50],
                        type=int,
                        nargs=1)

    args = vars(parser.parse_args())
    
    lstm = LSTM(model=args['model'][0], seq_maxlen=args['length'][0])
    lstm.train(args['iterations'][0], test_seq_len=args['test_length'][0])


main()
